Point Processing Techniques

In [1]:
import cv2
import numpy as np

ModuleNotFoundError: No module named 'cv2'

Image Negative

In [6]:
img = cv2.imread('Pattern-Recognition/Muki.jpeg',0)

To ascertain total numbers of rows and columns of the image, size of the image

In [7]:
m,n = img.shape

To find the maximum grey level value in the image

In [8]:
L = img.max()

Maximum grey level value  minus the original image gives the negative image

In [9]:
img_neg = L-img

convert the np array img_neg to a png image

In [10]:
cv2.imwrite('Cameraman_Negative.png', img_neg)

True

Thresholding without background. 
Let threshold =T.
Let pixel value in the original be denoted by r.
Let pixel value in the new image be denoted by s.
If r<T, s= 0
If r>T, s=255

In [2]:
T = 150

Create an array of zeros

In [1]:
import numpy as np

# Define variables
m, n = 5, 5  # Dimensions of the image
img = np.random.randint(0, 256, size=(m, n))  # Random grayscale image (values between 0 and 255)
T = 100  # Threshold value

# Initialize the output array
img_thresh = np.zeros((m, n), dtype=int)

# Apply thresholding
for i in range(m):
    for j in range(n):
        if img[i, j] < T:
            img_thresh[i, j] = 0
        else:
            img_thresh[i, j] = 255

# Print results
print("Original Image:")
print(img)
print("Thresholded Image:")
print(img_thresh)


Original Image:
[[ 40 132   0 113 228]
 [102 227 128 171  30]
 [  3  69  38  78  50]
 [210  93 123  76  61]
 [250 252  19 180 235]]
Thresholded Image:
[[  0 255   0 255 255]
 [255 255 255 255   0]
 [  0   0   0   0   0]
 [255   0 255   0   0]
 [255 255   0 255 255]]


In [13]:
import cv2
import numpy as np


# Image negative
img = cv2.imread('food.jpeg',0) 

# To ascertain total numbers of 
# rows and columns of the image,
# size of the image
m,n = img.shape

# To find the maximum grey level
# value in the image
L = img.max()

# Maximum grey level value minus 
# the original image gives the
# negative image
img_neg = L-img

# convert the np array img_neg to 
# a png image
cv2.imwrite('Cameraman_Negative.png', img_neg)

# Thresholding without background 
# Let threshold =T
# Let pixel value in the original be denoted by r
# Let pixel value in the new image be denoted by s
# If r<T, s= 0
# If r>T, s=255

T = 150

# create an array of zeros
img_thresh = np.zeros((m,n), dtype = int) 

for i in range(m):
	
	for j in range(n):
		
		if img[i,j] < T: 
			img_thresh[i,j]= 0
		else:
			img_thresh[i,j] = 255


# Convert array to png image
cv2.imwrite('Cameraman_Thresh.png', img_thresh)

# the lower threshold value
T1 = 100

# the upper threshold value
T2 = 180

# create an array of zeros
img_thresh_back = np.zeros((m,n), dtype = int)

for i in range(m):
	
	for j in range(n):
		
		if T1 < img[i,j] < T2: 
			img_thresh_back[i,j]= 255
		else:
			img_thresh_back[i,j] = img[i,j]

# Convert array to png image
cv2.imwrite('Cameraman_Thresh_Back.png', img_thresh_back)


[ WARN:0@0.022] global loadsave.cpp:241 findDecoder imread_('food.jpeg'): can't open/read file: check file path/integrity


AttributeError: 'NoneType' object has no attribute 'shape'